service: bcparks-ar-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: api
  region: ca-central-1
  lambdaHashingVersion: 20201221

package:
  individually: true
  patterns:
    - "!./**" # This causes Serverless to only package referenced source files

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-include-dependencies
functions:
  ###########
  # readConfig
  ###########
  readConfig:
    handler: lambda/readConfig/index.handler
    events:
      - http:
          method: GET
          path: /config

  ###########
  # Park
  ###########
  parkGet:
    handler: lambda/park/GET/index.handler
    events:
      - http:
          method: GET
          path: /park
          cors: true
  parkPost:
    handler: lambda/park/POST/index.handler
    events:
      - http:
          method: POST
          path: /park
          cors: true

  ###########
  # SubArea
  ###########
  subareaGet:
    handler: lambda/subarea/GET/index.handler
    events:
      - http:
          method: GET
          path: /subarea
          cors: true

  subareaPost:
    handler: lambda/subarea/POST/index.handlePost
    events:
      - http:
          method: POST
          path: /subarea
          cors: true

  subareaRecordLock:
    handler: lambda/subarea/POST/index.handleLock
    events:
      - http:
          method: POST
          path: /subarea/lock
          cors: true

  subareaRecordUnlock:
    handler: lambda/subarea/POST/index.handleUnlock
    events:
      - http:
          method: POST
          path: /subarea/unlock
          cors: true

  ###########
  # Export
  ###########
  exportInvokable:
    handler: lambda/export/invokable/index.handler
  exportGet:
    handler: lambda/export/GET/index.handler
    events:
      - http:
          method: GET
          path: /export
          cors: true

  ###########
  # Fiscal Year End
  ###########
  fiscalYearEndGet:
    handler: lambda/fiscalYearEnd/GET/index.handler
    events:
      - http:
          method: GET
          path: /fiscalYearEnd
          cors: true

  fiscalYearEndLock:
    handler: lambda/fiscalYearEnd/POST/index.lockFiscalYear
    events:
      - http:
          method: POST
          path: /fiscalYearEnd/lock
          cors: true

  fiscalYearEndUnlock:
    handler: lambda/fiscalYearEnd/POST/index.unlockFiscalYear
    events:
      - http:
          method: POST
          path: /fiscalYearEnd/unlock
          cors: true

resources:
  Resources:
    databaseTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: arTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
